### ISSUE TITLE
Question about demo_2_motor

### ISSUE THREAD

**Issue by laniakeawhite** [open-dynamic-robot-initiative/blmc_drivers#25]
Does this example need  hardware slider  connected to the A6,B6 pins of TI board?

**Comment by luator** [comment]
Yes, I think this demo uses the readings from the analogue inputs to set the target positions for the motors, so something like a hardware slider or similar device needs to be connected to the board.

**Comment by laniakeawhite** [comment]
@luator thank yout. I got it now.
I don't have sliders now, maybe i can try to simulate slider signal by code.

**Comment by laniakeawhite** [comment]
When test single motor using "demo2_motor",the motor oscillates hard, i have try many the PD params like [10,1],[5,0.1],[20,1]....
None of those PD params  prevent oscillation.
Does any one know what PD params can make motor spin smoothly?
