### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by STGRobotics** [open-dynamic-robot-initiative/blmc_drivers#8]
The description for CAN protocol used link does not work

https://atlas.is.localnet/confluence/display/AMDW/BLMC+-+CAN+Interface

**Comment by cajt** [comment]
second.

**Comment by jviereck** [comment]
hi @luator , @thomasfla , do you know if we have the CAN protocol documented outside of the institute wiki?

**Comment by luator** [comment]
I don't think so.  We should probably add it in the [firmware repository](https://github.com/open-dynamic-robot-initiative/mw_dual_motor_torque_ctrl) (along with other firmware documentation).

**Comment by jviereck** [comment]
Should we export the PDF version of the wiki page for now?

**Comment by luator** [comment]
Yes, that would be a good intermediate solution (I think converting the wiki formatting to markdown or rst will take some time).

**Comment by luator** [comment]
[BLMC_CAN_Interface-010720.pdf](https://github.com/open-dynamic-robot-initiative/blmc_drivers/files/4856546/BLMC_CAN_Interface-010720.pdf)

**Comment by thomasfla** [comment]
Thanks @luator 
I also think we should explain better the CAN vs SPI interfaces and reorganize the informations. 
At the moment the SPI protocol of the uDivers are documented in the master board repo: https://github.com/open-dynamic-robot-initiative/master-board/blob/master/documentation/BLMC_%C2%B5Driver_SPI_interface.md

Ideally I think SPI and CAN documentation should be moved to the a repo dedicated to the uDriver (witch is now part of the actuator_hardware) What do you think?

**Comment by luator** [comment]
I think it's best if the documentation of the interface lives in the repo of the corresponding firmware, which would be mw_dual_motor_torque_ctrl for CAN.  I'm not sure about the SPI version.  On the long term, I still would like to merge the two versions, then both would be in the same repo.  I will unfortunately not have time to look into this this in the near future, though :(

**Comment by MaximilienNaveau** [comment]
I am closing this issue as the doc is now in the open-source package.
Improvement in terms on documentation is always welcome and PR are appreciated^^
